### ISSUE TITLE
Excel parity milestone

### ISSUE THREAD

**Issue by dabreegster** [acteng/inspectorate_tools#50]
This first milestone represents the point where the new tool could effectively replace the Excel tool. Even if the design isn't ideal, it's feature-complete and has no blocking bugs. "Excel parity" doesn't mean exactly the same as the Excel version, just equivalent or better functionality. Big deviations are noted below.

[Burndown list recorded in issues](https://github.com/acteng/inspectorate_tools/issues?q=is%3Aopen+is%3Aissue+-label%3Anice-to-have)

- [ ] Everything in first round feedback docs triaged
- [ ] All unit tests passing
- [ ] DALOG diff after copied into Excel is manually checked

# Area check

Big changes:

- The scheme summary has a simple map from the Scheme Sketcher

# Cross-section

Big changes:

- The scheme summary has a simple map from the Scheme Sketcher
- The language has changed around "preferred" and "compromised" cross sections, with the range of "absolute minimum" to "desirable minimum" widths decoupled
- Pinch points are captured by map

# Route check

Big changes:

- The scheme summary has a simple map from the Scheme Sketcher
- Critical issues and policy conflicts are combined into one Problem Mapping Page, which is map-based
- JAT check is streamlined as a map interface
- Some result sections are skipped when appropriate (based on street vs path check)
- **Some percentages reported in results are off-by-one compared to Excel, due to rounding differences**
